# Generated by Django 3.2.6 on 2022-09-16 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price_api',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Название')),
                ('content', models.TextField(blank=True, verbose_name='Описание')),
                ('published', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
            ],
            options={
                'ordering': ['-published'],
            },
        ),
    ]
