# Generated by Django 3.2.6 on 2022-09-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('content', models.TextField(verbose_name='Описание')),
                ('img', models.ImageField(blank=True, upload_to='media/')),
            ],
        ),
    ]
